"""Generate Product_Info.xlsx from Cassagne & Vitailles data."""
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Cassagne_Vitailles"

# Headers
headers = [
    "SKU", "NAME", "NAME_CN", "COLOR", "REGION", "GRAPE_VARIETY",
    "PRICE_EUR", "ALCOHOL", "VINTAGE", "WINERY", "ACID", "TANNIN",
    "BODY", "SWEETNESS", "FLAVOR_PROFILE", "FOOD_PAIRING", "OCCASION",
    "TASTING_NOTES",
]
header_fill = PatternFill(start_color="2F5496", end_color="2F5496", fill_type="solid")
header_font = Font(color="FFFFFF", bold=True, size=11)
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = Alignment(horizontal="center")

# Wine data
wines = [
    {
        "sku": "CV-BL-001",
        "name": "Combarels Blanc",
        "name_cn": "孔巴雷尔白",
        "color": "white",
        "region": "Pays d'Oc, Languedoc, France",
        "grape": "Chardonnay, Viognier, Colombard",
        "price": 10.0,
        "alcohol": "13.0%",
        "vintage": 2023,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "",
        "body": "light",
        "sweetness": "dry",
        "flavor": "Citrus, white peach, acacia flowers, mineral notes, fresh almond",
        "food": "Oysters, grilled white fish, sushi, goat cheese salad, light appetizers",
        "occasion": "Aperitif, summer patio, casual gathering, seafood dinner",
        "notes": "A true concentrate of freshness. Crisp acidity with delicate floral and citrus notes, clean mineral finish. 94 pts (2023), 92 pts (2021).",
    },
    {
        "sku": "CV-RD-001",
        "name": "Combarels - De l'Ombre",
        "name_cn": "孔巴雷尔·暗影",
        "color": "red",
        "region": "Terrasses du Larzac, Languedoc, France",
        "grape": "Grenache, Syrah",
        "price": 10.0,
        "alcohol": "13.5%",
        "vintage": 2021,
        "winery": "Cassagne & Vitailles",
        "acid": "moderate",
        "tannin": "medium",
        "body": "medium",
        "sweetness": "dry",
        "flavor": "Fresh blackberry, currants, rosemary, oleander, oak leaf, cocoa",
        "food": "Charcuterie, roasted vegetables, grilled sausages, pizza, Mediterranean stew",
        "occasion": "Everyday drinking, casual gathering, BBQ, weeknight dinner",
        "notes": "Power, elegance, amplitude. Notes of rosemary. Fresh blackberry, currants, oak leaf, cocoa. Elegant, precise, racy tannins. 93 pts. Suckling 92 pts. Larsson 89 pts.",
    },
    {
        "sku": "CV-RD-002",
        "name": "Combarels - A la Lumiere",
        "name_cn": "孔巴雷尔·光芒",
        "color": "red",
        "region": "Terrasses du Larzac, Languedoc, France",
        "grape": "Grenache, Syrah",
        "price": 10.0,
        "alcohol": "14.0%",
        "vintage": 2021,
        "winery": "Cassagne & Vitailles",
        "acid": "moderate",
        "tannin": "medium",
        "body": "medium",
        "sweetness": "dry",
        "flavor": "Wild blackberry, wild strawberry, wild currants, liquorice, garrigue, toasted almond, tobacco",
        "food": "Grilled lamb, ratatouille, Provencal dishes, semi-hard cheese, braised pork",
        "occasion": "Casual dinner, weekend gathering, house wine, discovering Languedoc",
        "notes": "Wild blackberry, strawberry, currants, liquorice, garrigue. Dried blackcurrant, crushed raspberry, tobacco, toasted almond. 95 pts. Suckling 91 pts. Larsson 89 pts.",
    },
    {
        "sku": "CV-RD-003",
        "name": "Nimalaya - Vieux Carignan",
        "name_cn": "尼玛拉雅·老藤佳丽酿",
        "color": "red",
        "region": "Montpeyroux, Languedoc, France",
        "grape": "Carignan (old vines, planted 1954)",
        "price": 19.0,
        "alcohol": "14.0%",
        "vintage": 2022,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "medium",
        "body": "medium",
        "sweetness": "dry",
        "flavor": "Minerals, gunpowder, dark berries, thyme, sage, black olives, blackberry, caramelization, chocolate",
        "food": "Slow-roasted lamb shoulder, cassoulet, wild game, aged Comte, truffle dishes",
        "occasion": "Special dinner, wine enthusiast gathering, discovering old vine character",
        "notes": "Suckling 95 pts: minerals, gunpowder, dark berries. Beck 93/100: garrigues (thym, sauge), olives noires. Elegant, juteux. 96 pts (2020, 2022). 70-year-old vines.",
    },
    {
        "sku": "CV-RD-004",
        "name": "Les Chausmes",
        "name_cn": "肖姆",
        "color": "red",
        "region": "Montpeyroux, Languedoc, France",
        "grape": "Syrah, Grenache, Carignan",
        "price": 26.0,
        "alcohol": "14.5%",
        "vintage": 2022,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "strong",
        "body": "full",
        "sweetness": "dry",
        "flavor": "Graphite, dark spices, peppermint, cherry, plum, chocolate, vanilla, gunpowder",
        "food": "Braised beef short ribs, venison, duck confit, aged hard cheese, rich stews",
        "occasion": "Dinner party, fine dining, special celebration, impressive gift",
        "notes": "Suckling 94 pts: spice, chocolate, gunpowder. Beck 96/100: graphite, precision, puissance paradoxale. Larsson 93 pts: vanilla, dark fruit, powerful, creamy. 96 pts (2020, 2022).",
    },
    {
        "sku": "CV-RD-005",
        "name": "Clas Mani",
        "name_cn": "克拉玛尼",
        "color": "red",
        "region": "Terrasses du Larzac, Languedoc, France",
        "grape": "Syrah, Carignan, Grenache",
        "price": 28.0,
        "alcohol": "14.5%",
        "vintage": 2021,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "medium",
        "body": "full",
        "sweetness": "dry",
        "flavor": "Wild blackberry, plum, blackcurrant, blond tobacco, liquorice, eucalyptus, nutmeg, gunpowder, garrigue",
        "food": "Grilled rib-eye steak, lamb rack, wild boar, strong blue cheese, mushroom risotto",
        "occasion": "Special occasion, fine dining, wine collector, anniversary dinner",
        "notes": "Wild blackberry, plum, tobacco, liquorice. Suckling 95 pts: graphite, gunpowder, chocolate. Beck 95/100: tannins fins, soyeux, persistante. Larsson 95 pts: dense, garrigue. 2 years in Chassin casks. 96 pts.",
    },
    {
        "sku": "CV-GR-001",
        "name": "Les Homs",
        "name_cn": "奥姆",
        "color": "red",
        "region": "Vin de France (Languedoc)",
        "grape": "Grenache",
        "price": 38.0,
        "alcohol": "13.5%",
        "vintage": 2022,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "soft",
        "body": "light",
        "sweetness": "dry",
        "flavor": "Wild strawberry, red fruits, red berries, delicate freshness, subtle mineral",
        "food": "Salmon tartare, grilled tuna, Provencal vegetable tart, light poultry, fresh goat cheese",
        "occasion": "Fine dining, wine enthusiast discovery, elegant aperitif, summer evening",
        "notes": "Concentrate of freshness, wild strawberries, red berries. Supple, light yet long and structured. 6-8 months in concrete egg. 96 pts (2022).",
    },
    {
        "sku": "CV-GR-002",
        "name": "Les Celis",
        "name_cn": "瑟利",
        "color": "red",
        "region": "Vin de France (Languedoc)",
        "grape": "Grenache (100%)",
        "price": 38.0,
        "alcohol": "13.5%",
        "vintage": 2021,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "soft",
        "body": "medium",
        "sweetness": "dry",
        "flavor": "Wild red berries, roses, garrigue, stones, mild spices, pepper, wild strawberries, sour cherries, graphite",
        "food": "Duck breast, quail, lamb loin, truffle pasta, aged Brie, fine charcuterie",
        "occasion": "Special celebration, collector wine, fine dining, memorable gift",
        "notes": "98 pts: wild red berries, roses, garrigue. Master class in finesse and poise. Beck 96/100: graphite, tannins fins, Un grand vin. 30% whole bunches, 8 months Chassin barrels.",
    },
    {
        "sku": "CV-GR-003",
        "name": "Les Crouzets",
        "name_cn": "克鲁泽",
        "color": "red",
        "region": "Vin de France (Languedoc)",
        "grape": "Grenache (100%)",
        "price": 38.0,
        "alcohol": "14.0%",
        "vintage": 2022,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "medium",
        "body": "medium",
        "sweetness": "dry",
        "flavor": "Faded rose, dried strawberry, sage, tobacco, rosemary, wild blackberry, heather, bergamot, smoky, eucalyptus",
        "food": "Roasted squab, venison medallions, truffle risotto, aged Epoisses, wild mushroom dishes",
        "occasion": "Exceptional occasion, collector wine, investment, once-in-a-lifetime dinner",
        "notes": "From 50-year-old parcel. Beck 98/100: violettes, cerises noires, graphite. Vin d'anthologie, remarquable, brillant. 98 pts (2022), 99-100 pts (2023). Floral rose, sage, bergamot.",
    },
    {
        "sku": "CV-PP-001",
        "name": "Pesoul",
        "name_cn": "佩苏尔",
        "color": "red",
        "region": "Terrasses du Larzac, Languedoc, France",
        "grape": "Grenache, Syrah",
        "price": 108.0,
        "alcohol": "14.5%",
        "vintage": 2016,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "strong",
        "body": "full",
        "sweetness": "dry",
        "flavor": "Deep dark fruit, graphite, earth, intense tannin structure, exceptional depth",
        "food": "Prime aged beef, whole roasted lamb, truffle dishes, premium aged cheese",
        "occasion": "Exceptional celebration, collector investment, once-in-a-lifetime experience",
        "notes": "Suckling 96 pts: real depth and drive with tannins. Biodynamic. Exceptional micro-parcel, Dantesque conditions. Only best years. Wooden crate.",
    },
    {
        "sku": "CV-PP-002",
        "name": "Pendut",
        "name_cn": "庞迪",
        "color": "red",
        "region": "Terrasses du Larzac, Languedoc, France",
        "grape": "Syrah, Grenache",
        "price": 108.0,
        "alcohol": "14.5%",
        "vintage": 2016,
        "winery": "Cassagne & Vitailles",
        "acid": "high",
        "tannin": "strong",
        "body": "full",
        "sweetness": "dry",
        "flavor": "Dense dark fruit, vanilla, cream, powerful structure, velvety depth",
        "food": "Wagyu beef, slow-cooked wild boar, foie gras, mature Roquefort",
        "occasion": "Exceptional celebration, collector investment, once-in-a-lifetime experience",
        "notes": "Suckling 95 pts: dense, creamy, mostly Syrah, attractive vanilla undertone. Same micro-parcel as Pesoul. Two souls, one symbiosis. Only best years. Wooden crate.",
    },
]

keys = ["sku", "name", "name_cn", "color", "region", "grape", "price",
        "alcohol", "vintage", "winery", "acid", "tannin", "body",
        "sweetness", "flavor", "food", "occasion", "notes"]

for r, wine in enumerate(wines, 2):
    for c, key in enumerate(keys, 1):
        ws.cell(row=r, column=c, value=wine[key])

# Column widths
widths = [12, 35, 18, 10, 40, 35, 10, 10, 10, 22, 10, 10, 10, 10, 80, 60, 55, 120]
for i, w in enumerate(widths, 1):
    ws.column_dimensions[openpyxl.utils.get_column_letter(i)].width = w

output = r"D:\00_Programming\04_Aibot\wine-advisor\00_Product_Data\Product_Info.xlsx"
wb.save(output)
print(f"Excel saved: {len(wines)} wines, {len(headers)} columns -> {output}")
